### PR TITLE
Adds support for Android 1.5 until 2.1

### PR DESCRIPTION
**Pull request by chdorner**
- Implements setSelection() if smoothScrollBy is not available (< 2.2)
- Workaround for getPointerCount() which is unavailable in 1.5 (it's always 1 in 1.5)
- Uses getHistoricalY with only one parameter when < Android 2.0

### CODE REVIEW

**Comment by chdorner** [comment]
Oh, and I also moved the drawables from drawable-hdpi to the drawable folder (for Android 1.5)

**Comment by johannilsson** [comment]
Wow, this works great!

I will soon push this, I've made a small change though. I've moved the drawables back to drawables-hdpi for the library project, but added them to drawables folder in the example project. Because of the small percentage of 1.5 I don't think it worth to support 1.5 direct from the library. Instead 1.5 users need to move the drawables them self to the drawable folder for their projects.

Thank you again, I know this will be very appreciated by many users.

**Comment by chdorner** [comment]
Thanks for adding the chances and the promotion on Twitter :)

I began implementing it into the WordPress for Android app and discovered some glitched, will check in the next days if those are problems on the PullToRefresh or WordPress side.

**Comment by johannilsson** [comment]
No problem, this was a very welcomed contribution.

It looks like the top padding is not longer divided with two any more, this was there to simulate a more resistant drag, that might be one of the glitches you're experienced?

**Pull request merged**
