### PR TITLE
Add German, Japanese, Chinese (traditional and simplified) translations

### PR DESCRIPTION
**Pull request by keverets**

### CODE REVIEW

**Comment by ru-alxr** [comment]
please add Russian:

```
./values-ru/
    <string name="app_name">pulltorefresh</string>
    <string name="pull_to_refresh_pull_label">Потяните для обновления&#8230;</string>
    <string name="pull_to_refresh_release_label">Отпустите для обновления&#8230;</string>
    <string name="pull_to_refresh_refreshing_label">Загрузка&#8230;</string>
    <string name="pull_to_refresh_tap_label">Кликните для обновления&#8230;</string>
```

**Comment by johannilsson** [comment]
Thanks @keverets, great work!

@ru-alxr would you like to send a PR with the russian translations?

**Comment by ru-alxr** [comment]
@johannilsson sorry, I cannot:
aleksandr@workstation:~/android-pulltorefresh$ git push origin russian

```
aleksandr@workstation:~/android-pulltorefresh$ git push origin russian
Username for 'https://github.com': ru-alxr
Password for 'https://ru-alxr@github.com': 
error: The requested URL returned error: 403 while accessing https://github.com/johannilsson/android-pulltorefresh.git/info/refs
fatal: HTTP request failed
```

and here git config

```
[core]
    repositoryformatversion = 0
    filemode = true
    bare = false
    logallrefupdates = true
[remote "origin"]
    fetch = +refs/heads/*:refs/remotes/origin/*
    url = https://github.com/johannilsson/android-pulltorefresh.git
[branch "master"]
    remote = origin
    merge = refs/heads/master
```

**Comment by johannilsson** [comment]
I see, you need to fork the repository first.

From github.com there's an fork button on the top right corner, next to star and watch. When you hit that button a copy of the current source/repo will be copied to a new repository to your account. This is the library you clone, commit and push your changes to. When that is done you can create a pull request. GitHub will automatically suggest this to you if you visit the repository through a browser. When that is done I can merge the changes into this repo.

I can do the changes if you want, but it's always fun to get a pull request accepted on a project :)

**Comment by ru-alxr** [comment]
@johannilsson  Thanks a lot! I'll try to do this way.

**Comment by ru-alxr** [comment]
@johannilsson  Hello, apply please this - https://github.com/johannilsson/android-pulltorefresh/pull/79

**Comment by johannilsson** [comment]
Thank you! :+1:

**Pull request merged**
